# Generated by Django 5.0.6 on 2024-08-09 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DroneCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender_value', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], max_length=10)),
                ('no_of_races', models.PositiveIntegerField()),
                ('inserted_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('manufacturing_date', models.DateTimeField(auto_now_add=True)),
                ('drone_participated_in_at_least_one_competition', models.BooleanField(default=False)),
                ('inserted_timestamp', models.DateTimeField(auto_now=True)),
                ('drone_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drone', to='drones_app.dronecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_value', models.PositiveIntegerField(help_text='measured in feet')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drones_app.drone')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drones_app.pilot')),
            ],
        ),
    ]
