# Generated by Django 5.0.6 on 2024-08-09 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones_app', '0002_alter_dronecategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drone',
            options={'ordering': ['name']},
        ),
    ]
