# Generated by Django 5.0.6 on 2024-08-10 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones_app', '0004_alter_competition_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pilot',
            options={'ordering': ['name']},
        ),
    ]
